# Generated by Django 2.2.5 on 2019-12-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('enabled', models.BooleanField(default=True, help_text='軟刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('email', models.CharField(help_text='登入帳號Email', max_length=256, unique=True)),
                ('password', models.CharField(help_text='密碼', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='軟刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('name', models.CharField(help_text='部門名稱', max_length=64)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='軟刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('name', models.CharField(help_text='角色權限名稱', max_length=64, unique=True)),
                ('description', models.CharField(help_text='角色權限描述', max_length=256, null=True)),
                ('role_manage', models.SmallIntegerField(default=0, help_text='帳號權限')),
                ('daily_rate', models.SmallIntegerField(default=0, help_text='每日考核權限')),
                ('report', models.SmallIntegerField(default=0, help_text='考核報表權限')),
            ],
            options={
                'db_table': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='WorkDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='軟刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('date', models.DateField(help_text='日期')),
                ('status', models.BooleanField(help_text='狀態')),
            ],
            options={
                'db_table': 'WorkDate',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='軟刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('employee_number', models.CharField(help_text='員工編號', max_length=32, unique=True)),
                ('account', models.EmailField(help_text='員工帳號(信箱)', max_length=32, unique=True)),
                ('password', models.CharField(help_text='員工密碼', max_length=64)),
                ('cn_name', models.CharField(help_text='員工中文姓名', max_length=64)),
                ('en_name', models.CharField(help_text='員工英文姓名', max_length=64)),
                ('status', models.BooleanField(help_text='員工啟用狀態')),
                ('remarks', models.CharField(help_text='備註', max_length=1024, null=True)),
                ('entry_date', models.DateField(blank=True, help_text='入職時間', null=True)),
                ('leave_date', models.DateField(blank=True, help_text='離職時間', null=True)),
                ('department', models.ForeignKey(help_text='部門編號', on_delete=django.db.models.deletion.CASCADE, related_name='User', to='api.Department')),
                ('permission', models.ForeignKey(help_text='權限編號', on_delete=django.db.models.deletion.CASCADE, related_name='User', to='api.Permission')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='SeasonScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='軟刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('rate_season', models.CharField(help_text='考核季', max_length=16)),
                ('complete_score', models.FloatField(help_text='完成度分數')),
                ('quality_score', models.FloatField(help_text='品質分數')),
                ('special_score', models.FloatField(help_text='特殊分數')),
                ('attitude_score', models.FloatField(help_text='態度分數')),
                ('avg_score', models.FloatField(help_text='季考核平均分數')),
                ('user', models.ForeignKey(help_text='員工流水號', on_delete=django.db.models.deletion.CASCADE, related_name='SeasonScore', to='api.User')),
            ],
            options={
                'db_table': 'SeasonScore',
            },
        ),
        migrations.CreateModel(
            name='RewardsAndPunishments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='軟刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('year_month', models.CharField(help_text='年度月份', max_length=16)),
                ('record', models.CharField(help_text='紀錄', max_length=128)),
                ('description', models.CharField(help_text='補充', max_length=128)),
                ('user', models.ForeignKey(help_text='員工流水號', on_delete=django.db.models.deletion.CASCADE, related_name='RewardsAndPunishments', to='api.User')),
            ],
            options={
                'db_table': 'RewardsAndPunishments',
            },
        ),
        migrations.CreateModel(
            name='MonthScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='軟刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('rate_month', models.CharField(help_text='考核月份', max_length=16)),
                ('complete_score', models.FloatField(help_text='完成度分數')),
                ('quality_score', models.FloatField(help_text='品質分數')),
                ('special_score', models.FloatField(help_text='特殊分數')),
                ('attitude_score', models.FloatField(help_text='態度分數')),
                ('error_mark', models.IntegerField(help_text='錯誤標記')),
                ('avg_score', models.FloatField(help_text='月考核平均分數')),
                ('bunus', models.IntegerField(help_text='月獎金', null=True)),
                ('user', models.ForeignKey(help_text='員工流水號', on_delete=django.db.models.deletion.CASCADE, related_name='MonthScore', to='api.User')),
            ],
            options={
                'db_table': 'MonthScore',
            },
        ),
        migrations.CreateModel(
            name='DayScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='軟刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('rate_day', models.DateField(help_text='考核日期')),
                ('complete_score', models.FloatField(help_text='完成度分數')),
                ('quality_score', models.FloatField(help_text='品質分數')),
                ('special_score', models.FloatField(help_text='特殊分數')),
                ('attitude_score', models.FloatField(help_text='態度分數')),
                ('error_mark', models.IntegerField(default=0, help_text='錯誤標記')),
                ('avg_score', models.FloatField(help_text='日考核平均分數', null=True)),
                ('status', models.BooleanField(help_text='考核狀態')),
                ('manager', models.ForeignKey(help_text='考核主管編號', on_delete=django.db.models.deletion.CASCADE, related_name='rate_DayScore', to='api.User')),
                ('user', models.ForeignKey(help_text='員工流水號', on_delete=django.db.models.deletion.CASCADE, related_name='owner_DayScore', to='api.User')),
            ],
            options={
                'db_table': 'DayScore',
            },
        ),
        migrations.CreateModel(
            name='AdminTokens',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='api.Admin')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'abstract': False,
            },
        ),
    ]
